server:
  port: 2001
spring:
  application:
      #应用名称，可写可不写
    name: reggie
      #数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://43.142.101.212:3306/reggie
      username: root
      password: 86530890a_


      #mybatisPlus配置
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 10000000
    #主键生成策略
  global-config:
    db-config:
      id-type: ASSIGN_ID



